#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Stuttgart analysis results file generated by APyT."""

# pylint: disable=duplicate-code

import os
import numpy as np

from ifes_apt_tc_data_modeling.utils.pint_custom_unit_registry import ureg
from ifes_apt_tc_data_modeling.utils.custom_logging import logger
    import pandas as pd


class ReadStuttgartApytMetadataFileFormat:
    """Read metadata of an entry from the db.yaml-style database-in-a-file as used by APyT."""

    def __init__(self, file_path: str):
        pass

    def get_metadata(self, database_entry: int = 0):
        """Read metadata of a specific database entry."""
        pass

class ReadStuttgartApytSpectrumAlignFileFormat:
    """Read results from the text file that an `apyt_spectrum_align --no-sql 1` call generates."""

    def __init__(self, file_path: str):
        expected_single_header = '# m/q (amu/e)    counts'
        with open(file_path, 'r') as fp:
            first_line = fp.readline().strip()

            if first_line == expected_single_header:
                self.df = pd.read_csv(file_path, delim_whitespace=True, comment='#')
            else:
                logger.error("Expected First line does not match the expected header. Found: '{first_line}'")

    def get_complete_spectrum(self):
        """Read complete (binned) mass spectrum."""
        pass

class ReadStuttgartApytSpectrumFitFileFormat:
    """Read results from text file(s) that an `apyt_spectrum_fit --no-sql 1 "{'W': ((3,), 0.0158)}` call generates."""

    def __init__(self, file_path: str):
        pass

class ReadStuttgartApytReconstructionFileFormat:
    """Read results from the text file that an `apyt_reconstruction --no-sql --module classic 1` call generates."""

    def __init__(self, file_path: str):
        pass

    def get_reconstructed_positions(self):
        """Read xyz columns."""
        pass

    def get_ion_type(self):
        """Read ion identity."""
        pass
